### ISSUE TITLE
Rename BlockingQueueDispatcher to EventLoopDispatcher?

### ISSUE THREAD

**Issue by daschl** [reactor/reactor#265]
Just thought about that when looking at the naming thing.. Wouldn't it make more sense to rename it to EventLoopDispatcher? Since that's also the terminology used when referring to it through the DispatcherType.

**Comment by JernejJerin** [comment]
Hi!

I am looking in the dispatch folder and I cannot find the EventLoopDispatcher. Is this now SingleThreadDispatcher?

**Comment by jbrisbin** [comment]
`SingleThreadDispatcher` is an abstract class. The old `BlockingQueueDispatcher` was obsoleted in favor of the `RingBufferDispatcher`. But there is a `BlockingQueue`-backed `Dispatcher` called the `TailRecurseDispatcher` which simply trampolines tasks.

Are you creating these manually rather than pulling them from the `Environment`?

**Comment by JernejJerin** [comment]
I was just reading a rather old article about reactor (http://tech.kinja.com/playing-with-reactor-626741403) and it mentions the following:

>Event loop (provides a single-threaded event loop)

So I downloaded v2.0.0.RC1 to fiddle with it and found out, that it is not there anymore. So this single threaded event loop is now represented by RingBufferDispatcher?

**Comment by jbrisbin** [comment]
> So this single threaded event loop is now represented by RingBufferDispatcher?

TL;DR yes.
