### ISSUE TITLE
ThreadPoolExecutorDispatcher discards events dispatched on a thread for which the context class loader is the same as the context class loader on which the dispatcher was created 

### ISSUE THREAD

**Issue by jfitzpatrick99** [reactor/reactor#336]
We are using the reactor framework for an application we are developing. After looking at all of the various dispatchers I decided to use the ThreadPoolExecutorDispatcher. In the course of doing testing, I noticed that sometimes, dispatched events were not being executed. On code inspection, I noticed the following code in the reactor.event.dispatch.AbstractLifecycleDispatcher class that is used to dispatch events for the ThreadPoolExecutorDispatcher implementation:

``` java
    @Override
    public <E extends Event<?>> void dispatch(Object key,
                                              E event,
                                              Registry<Consumer<? extends Event<?>>> consumerRegistry,
                                              Consumer<Throwable> errorConsumer,
                                              EventRouter eventRouter,
                                              Consumer<E> completionConsumer) {
        Assert.isTrue(alive(), "This Dispatcher has been shut down.");

        try {
            Task task;
            boolean isInContext = isInContext();
            if (isInContext) {
                task = allocateRecursiveTask();
            } else {
                task = allocateTask();
            }

            task.setKey(key)
                    .setEvent(event)
                    .setConsumerRegistry(consumerRegistry)
                    .setErrorConsumer(errorConsumer)
                    .setEventRouter(eventRouter)
                    .setCompletionConsumer(completionConsumer);

            if (isInContext) {
                addToTailRecursionPile(task);
            } else {
                execute(task);
            }
        }catch(Exception e){
            e.printStackTrace();
            System.exit(1);
        }
    }
```

As you can see, a check is done to see if the current thread context class loader matches the context class loader for the thread on which the dispatcher was created. The truth of this condition is stored in the boolean variable isInContext. If the flag is false, the execute method is called for the created task otherwise the addToTailRecursion method is called. The addToTailRecursion method is defined as:

``` java
    protected void addToTailRecursionPile(Task task) {
    }
```

This method is not overridden in the either of the sub-classes which are  reactor.event.dispatch.AbstractMultiThreadDispatcher and reactor.event.dispatch.ThreadPoolExecutorDispatcher.

The code is very deliberate but this seems to be a bug, For now I have implemented a custom dispatcher which extends from the ThreadPoolExecutorDispatcher where I override the dispatch method with an implementation that ensures that the task is executed. Any further guidance would be greatly appreciated.

Thanks,

John

**Comment by ymolists** [comment]
Hi All.

Interesting ... I am one of the developers with jfitzpatrick99. Can i ask the following:

1) if all i wanted was a mpsc (multi producer single consumer) queue out of the reactor whats the correct way to use the reactor so that it is able to queue events from multiple queues but service them from only one thread ? A mpmc (multi producer multi consumer) would be even nice !

2) If the above is not possible what can i do to turn the reactor event bus into a spsc (single producer single consumer) queue  ? I know that with an spsc i can turn it into a mpsc by having multiple spsc queues. Our queues can be bounded queues for example.

3) How do you queue items in a deterministic order into the rector and guaranty that the events will be executed in the same order they were entered ?

I know that there are other libraries better suited for this type of use cases like jctools or the disruptor itself. But i was wondering that maybe i am missing something that does the same thing in the reactor event bus.

**Comment by ymolists** [comment]
oops .. my coworker found this old entry. He is not jfitzpatrick99 ... My apologies for the confusion !
