### ISSUE TITLE
why not use java8

### ISSUE THREAD

**Issue by boboyada** [reactor/reactor#360]
why not use java8/lambda/function/stream? Standing on Shoulders of Giants;
the next few years,more and more developers will use java8

**Comment by sdeleuze** [comment]
As already discussed with @smaldini, I really hope to see a Java 8 based Reactor. Maybe for an upcoming Reactor 3.0?

**Comment by ifesdjeen** [comment]
We're using reactor with jdk8 and are very happy with it, nothing prevents you and there are basically all optimisations available too

**Comment by sdeleuze** [comment]
Indeed, but it is more about using JDK8 `java.util.function` types instead of Reactor own types. The biggest issue I see about this is Android, that's why staying as it is for Reactor 2.x and switch to Java 8 on Reactor 3.x could be a good compromise.

IMO, it is nice to take the time and the required steps to do this transition, but we can't stick on Java 6 forever for server side use case just because of Android.
