### ISSUE TITLE
Add map() and flatMap() equivalent to Promise

### ISSUE THREAD

**Issue by sdeleuze** [reactor/reactor#416]
I am using Reactor 2 to build an Http Server and in several place I use `Promise` in my API to express that a method will return a single data (or no data at all with `Promise<Void>`). I previously used `CompletableFuture` for that but since Reactor provide a `Promise` with a better API, I would like to use it.

The issue is that Promise does not have equivalent map() and flatMap() operations. Obviously, It is possible to do it by converting the promise to a stream, but I really think promise should allow to transform the data natively like `CompletableFuture`. See this post for more details http://www.nurkiewicz.com/2013/05/java-8-definitive-guide-to.html.

Last point, `Promise` is a great advantage of Reactor compared to RxJava (they plan to add it, but no real planning yet, see https://github.com/ReactiveX/RxJava/issues/1594 for more details), so it would be awesome to have a real powerful `Promise` to strengthen this advantage.

**Comment by jbrisbin** [comment]
I used to feel this way, when `Promise` was just a subclass of `Stream`. But now I don't think a `Promise` and a `Stream` are the same thing.

If you look inside a Promise, the `on{Success|Error|Complete}` methods are just doing a `stream().lift()`, `stream().recover()` or `stream().observe()` anyway, so dealing with the downstream actions is something not really the responsibility of a `Promise`. Instead, a `Promise` is a `Publisher` that sends data downstream once a value is available.

IMO there isn't a clear advantage to going back to a `Promise` being a subclass of `Stream`. I think having the extra step of calling `.stream()` to get those operations isn't too burdensome since that's all a `Promise` is doing internally anyway.

**Comment by smaldini** [comment]
I think the transformation and merge one (a.k.a, monad or map/flatmap) is what Sebastien is looking after. I can't see operations making use of any interface but at least it would give a consistent experience ?

**Comment by sdeleuze** [comment]
Yes @smaldini, that's what I am looking after.

I agree that `Promise` should not be a subclass of `Stream`, since a lot of operations only makes sense with multiple values, but I think it should contains the transformation operation that make sense when emitting a single value.

For example, having methods to change a `Promise<T1>` to `Promise<T2>` without using `stream()` is something that is needed all the time in the application I write, and **all** Promise implementation I am aware of implement it.

There is a lot of use cases, for example waiting multiple promises with `Promises.when(Promise<T1> p1, Promise<T2> p2)` and transform the `Promise<Tuple2<T1, T2>>` into a `Promise<T3>`.
