### ISSUE TITLE
broken links to api docs

### ISSUE THREAD

**Issue by juanmf** [reactor/reactor#422]
Through out the docs there are links to 
http://reactor.github.io/docs/api/reactor/core/* that yield 404.
for instance:
http://reactor.github.io/docs/api/reactor/core/composable/Deferred.html

**Comment by jbrisbin** [comment]
We need to update the wiki. The new location of documentation is on the new website:

http://projectreactor.io/docs/

Note that `Deferred` is from Reactor 1.x and all new development should be on 2.0 because it includes Reactive Streams integration and is a breaking change in a number of ways from 1.1.

**Comment by juanmf** [comment]
Thanks for the heads up!
