### ISSUE TITLE
Why onError callback is not fired?

### ISSUE THREAD

**Issue by avarabyeu** [reactor/reactor#485]
Hi all! Here is the code snippet:
```java
		Environment environment = new Environment();
		Environment.assign(environment);
		Promises.task(environment, environment.getDefaultDispatcher(), () -> {
			throw new RuntimeException("Some Exception");
		}).onError(t -> System.out.println("ERROR!")).onSuccess(s -> System.out.println("COMPLETED" + s));

		environment.shutdown();
```
I was wondering why 'onError' callback is not fired when Promise's supplier throws error.

**Comment by smaldini** [comment]
Def a bug to investigate and if resolution goes on will be in our 2.0.4

**Comment by jbrisbin** [comment]
@smaldini This is because the `Exception` is being thrown and not caught in the `Runnable`:

https://github.com/reactor/reactor/blob/master/reactor-stream/src/main/java/reactor/rx/stream/SupplierStream.java#L82

If you call `Environment.assignErrorJournal()` you'll see the error reported in the `Environment`.

**Comment by jbrisbin** [comment]
@avarabyeu @smaldini I'll push a quick fix that I just tested and seems to work (wrapping a try/catch around the `.get()` call above).
