### ISSUE TITLE
HashWheelTimer should be able to clear all scheduled tasks

### ISSUE THREAD

**Issue by Chumper** [reactor/reactor#497]
I currently have the problem that I need to clear all scheduleded tasks from time to time.
There is no possibility for me at the moment. Therefore i subclassed the SimpleHashWheelTimer from the 2.0.0 Release Candidate and added a clear all method.

Alternative would be, that a timer can be instructed to stop the underlaying timer thread in order to be collected by the GC.

I would prefer a method on the HashWheelTimer to cancel all registrations plus the possibility to instruct a timer to dispose all resources.

**Comment by smaldini** [comment]
We can add some lifecycle hook indeed that would run immediately all pending task implementing lifecycle or something else cancel() method.

**Comment by jbrisbin** [comment]
FWIW we've changed a few things since then. There is no `SimpleHashWheelTimer` any more. Everything uses the internal `RingBuffer` style which means we don't maintain a list of registrations like we did. Implementing this would likely involve making a `WaitStrategy` aware of a global switch which we could flip that would unblock waiting and immediately cancel pending `TimerPausables`.
