### ISSUE TITLE
Issue canceling a streams created from static Stream.* methods.

### ISSUE THREAD

**Issue by masterav10** [reactor/reactor#505]
Calling the `Control .cancel()` method from a stream created by a static Stream method appears to cancel all future methods.

I've attached a test case that demonstrates the correct behavior for a Broadcaster, but incorrect behavior for two streams connected using `Streams.combineLatest(..)`

https://gist.github.com/masterav10/c2278be51e25a0a1752f

My understanding was that future consume(s) would cause values to propagate through the stream again.

Tested using 2.0.3.RELEASE.

**Comment by smaldini** [comment]
The combinatory actions are not replayable (hot streams) since all they do is combining sequences.
Therefore they are considered like Broadcaster, and will cancel if all subscribers have cancelled. If you want to prevent that, use combineLatest().keepAlive() to prevent the cancel to propagate to combineLatest. The difference with Broadcaster is the combinatory operation has more state verification and will actually stop working after cancel where broadcaster itself is just a pass through and may continue to work even after cancel.

**Comment by masterav10** [comment]
Interesting. So I tried adding keepAlive() as such:
     `Stream<Tuple2<String, String>> s = Streams.combineLatest(s1, s2, t -> t).keepAlive();`
I also tried broadcast(), which didn't work either. I can try sleuthing a bit more. 

So now I'm confused. I know Broadcaster is a hot stream. The combinatory functions are also hot? I thought they were just a passthrough, and would inherit the hot or cold behavior from the source?.

**Comment by smaldini** [comment]
You're right we fixed that in the reactor-stream soon to be 2.5.0.M1 : http://next.projectreactor.io/stream/docs/api/reactor/rx/Stream.html#combineLatest-reactor.fn.Function-org.reactivestreams.Publisher...-

**Comment by smaldini** [comment]
Also have a look at the new Stream#publish method that allows arbitrary cancellation/subscription outside the flow.

**Comment by masterav10** [comment]
Good work, really like where 2.5.0 is.
