### ISSUE TITLE
Object Pool Recyclable Objects which you can

### ISSUE THREAD

**Issue by sirinath** [reactor/reactor#526]
More efforts can be put into Object Pool Recyclable Bbject (http://projectreactor.io/docs/api/reactor/core/support/Recyclable.html). Though this interface is defined, recycling does not seem to be used as much as it can be.

**Comment by sirinath** [comment]
Have a look at: https://github.com/chrisvest/stormpot

**Comment by sirinath** [comment]
Quite a few instances of object creation in `EventBus.notify`.

**Comment by ifesdjeen** [comment]
In my opinion, the only object that's "redundant" or poolable is `Event`, which is in our experience also redundant: we had to work around it in order to make Reactor Event-less. This was also adressed in [reactor-pipe](https://github.com/reactor/reactor-extensions/tree/master/reactor-pipe), where `Firehose` accepts any object as a value, without additional wrapper.

Latest developments has also shown that it's possible to completely replicate `EventBus` with `Pipe`. Maybe when `Pipe` matures, it can be used as an `EventBus`?

**Comment by sirinath** [comment]
Can you get rid off event? This was something I was asking even before @smaldini joined the project.

**Comment by ifesdjeen** [comment]
We effectively have no `Event` in `Pipe`. We could find no use of Event for our use-case (which is very broad).

**Comment by sirinath** [comment]
Can you get rid if having to wrap the object as you have to create one wrapper object hence more GC.

**Comment by ifesdjeen** [comment]
Once again, pooling is extremely complicated in case of `Event` object. Extremely complicated. We've tried that and opted out for not having it at all.

**Comment by sirinath** [comment]
Not having to use `Event` to wrap a object is the best way if it is possible.

**Comment by ifesdjeen** [comment]
We've gotten rid of `Event` by now.
