### ISSUE TITLE
Issue sending events from thread created in handler

### ISSUE THREAD

**Issue by stanliberman** [reactor/reactor#545]
We've ran into an issue with Reactor where events were not getting dispatched. After some debugging we boiled it down to `AbstractLifecycleDispatcher.dispatch()` not routing the event since it's determined to be a recursive by `inContext()` check.

Turned out that the thread that was sending the message was created on dispatcher thread and thus inherited `ContextClassLoader`.

I have a simple test case to demonstrate. One solution is to instantiate the Thread beforehand, but it's not possible to do in the case of a 3rd party library we're using. Thread is created and kicked off as a result of processing an event.

I'm wondering if it's a bug or an issue with our usage of Reactor.

Thanks,
Stan

``` java
    @Test
    public void testReactorFail() throws Exception
    {
        final EventBus eventBus = new EventBusSpec()
                .env(new Environment()) // Comment out to use immediate dispatcher and pass the test
                .get();

        final CountDownLatch latch = new CountDownLatch(1);

        eventBus.on($("START"), e -> new Thread(() -> {eventBus.notify("DATA", Event.wrap(null));}).start());
        eventBus.on($("DATA"), e -> latch.countDown());

        eventBus.notify("START", Event.wrap(null));

        assertFalse(latch.await(1, TimeUnit.SECONDS));
    }
```

**Comment by smaldini** [comment]
Should be fixed with the 2.1 internal refactor. The proposition in 2.1 (branch dispatcher-to-processor) is that you will be able 
- To choose a "managed" async boundary (eventBusSpec.processor(Processors.asyncService().get())) with the actually similar call to isInContext internally to dispatch the data. 
- Or you will be able to pick a "bare metal" async boundary which doesn't do any isInContext (eventBusSpec.processor(Processors.async()) but reentrance has to be managed with another async boundary or mechanism then, like notifying inside the event thread you are mentioning. Otherwise you might risk a deadlock.

**Comment by stanliberman** [comment]
Thanks! That sounds like it would help.

However, I still think that behavior is not correct, since I'm notifying from a **thread created in handler**. This is not a case of async dispatch. If thread ID, for example, was used to determine recursion then this issue would not occur.

**Comment by smaldini** [comment]
A pluggable strategy would be interesting, the purpose of the equality check is quite fast indeed is to be relatively neutral in terms of perf, but a bit more flexibility could help solving this case of reentrance.
