### ISSUE TITLE
"From Custom Reactive Publishers" example in doc

### ISSUE THREAD

**Issue by jebl01** [reactor/reactor#557]
Can't get the following example (from doc) to work:

``` java
final Stream<String> stream1 = Streams.create(new Publisher<String>() {
  @Override
  public void subscribe(Subscriber<? super String> sub) {
    sub.onSubscribe(new Subscription() { 
      @Override
      public void request(long demand) {
        if(demand == 2L){
          sub.onNext("1");
          sub.onNext("2");
          sub.onComplete();
        }
      }

      @Override
      public void cancel() {
        System.out.println("Cancelled!");
      }
    });
  }
});

final Stream<String> stream2 = Streams.create(sub -> {
  sub.onNext("3"); 
  sub.onNext("4");
  sub.onComplete();
});

final AtomicInteger counterSubscriber = new AtomicInteger();

Stream<String> deferred = Streams.defer(() -> {
  if (counterSubscriber.incrementAndGet() == 1) { 
    return stream1;
  }
  else {
     return stream2;
  }
});

deferred
  .consume(s -> System.out.printf("%s First subscription = %s%n", Thread.currentThread(), s));
deferred
  .consume(s -> System.out.printf("%s Second subscription = %s%n", Thread.currentThread(), s));
```

stream2 happily produces values, but not stream1. It seems like _request_ is never invoked on the created _Subscription_. Yes, I removed the `if(demand == 2L){` statement.

**Also** - it would be nice with expected output documented for all examples :-)

**Comment by akarnokd** [comment]
Hi. 

First of all, it is unlikely a downstream will request exactly 2 elements from stream 1, but by removing the if statement, that should emit values (although it is not reentrant safe). The example, after removing if, works with RxJava 2.0. 

Second, the stream2 violates the RS spec because one has to call `onSubscribe` on the `Subscriber` before any call to the other `onXXX` methods. It runs because luckily, nothing tries access the missing `Subscription`. But as soon as you apply take(1), you'll get an NPE.

I think the problem is in PublisherStream:65 where the subscription is set but no request is issued. I don't fully understand the internals, but it is common in RxJava 2.0 that we forward the Subscription to the child Subscriber, in this case the `thiz` instance so it can express its requests.

**Comment by smaldini** [comment]
Hi @akarnokd, @jebl01 

Create in 2.0 was a specific and confusing in the sense it allowed for no onSusbcribe call. It has been renamed for now "withOverflowSupport" in 2.1 but might disappear after we refocused our operations on what we need in reactor-core especially. So effectively the 2.0.x create() allows to directly call onNext(), and it might be a bug with this case. Even in 2.0.x there is something called PublisherFactory.forEach()  (now called Publishers.create() in 2.1 snapshots) that allows you to react on events in a rentrant safe way.

**Comment by jebl01** [comment]
@akarnokd Yes, demand == 2 is unlikely (as I also wrote in the issue). This example is taken as is from the docs (http://projectreactor.io/docs/reference/#_from_custom_reactive_publishers).

@smaldini I was about to fix this today, but I couldn't get the project to work with IntelliJ (any tip)?! I suspect that it would work as expected if the "else if" on row 83 in PublisherStream was changed to a simple if-statement. Later I got what I wanted by using Streams.wrap instead, but I still argue that the docs are misleading (and very thin) on creating custom reactive publishers...

**Comment by smaldini** [comment]
mhh whats wrong with IntelliJ ? I use gradle import on reactor/build.gradle and thats about it. Make sure you are on 2.0.x branch tho. And I do 200% agree with you on the doc I am working on building a CI for auto update on them so me and contributors are more encouraged on this part :)

**Comment by jebl01** [comment]
Believe I was on master...
